spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/db_home_transfer?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
   # url:  jdbc:mysql://mysql/db_home_transfer?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 0228


server:
  servlet:
    #josn数据返回中文乱码解决
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#下面两个配置 在tomcat中无用，只在springboot内置的tomcat中生效
#因为端口号是tomcat配置文件中配置的 上下文路径是打包的名字
    context-path: /home/
  port: 8220

mybatis:
  type-aliases-package: com.mmry.bean
  mapper-locations: classpath:mapper/*.xml
